version: '3'
services:
  app:
    build: .
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    image: redis:6
    volumes:
      - redis-data:/data
volumes:
  mysql-data:
  redis-data:
